# Generated by Django 5.2.6 on 2025-11-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_yummy', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='User_ID',
            new_name='User',
        ),
    ]
