# Generated by Django 5.2.6 on 2025-11-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_yummy', '0003_rename_user_id_restaurant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummy_yummy.restaurant')),
            ],
        ),
    ]
