# Generated by Django 5.2.6 on 2025-11-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_yummy', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
    ]
