# Generated by Django 5.2.6 on 2025-11-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_yummy', '0007_alter_product_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummy_yummy.restaurant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
