# Generated by Django 5.2.8 on 2025-11-22 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_yummy', '0010_cart_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='product')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=100)),
                ('quatity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(default='Wait')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummy_yummy.product')),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummy_yummy.restaurant')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
