# Generated by Django 5.2.8 on 2025-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_yummy', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
